version: '3.8'

services:
  app:
    container_name: backend-spectacle
    image: backend-spectacle:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - 3001:3001
    networks:
      - spectacle
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
networks:
  spectacle:
