version: "3.8"

services:
  app:
    container_name: frontend-spectacle
    image: frontend-spectacle:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - 3000:3000
    networks:
      - spectacle
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
networks:
  spectacle:
